# Generated by Django 4.2.23 on 2025-08-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_job_created_by_job_employer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="employer", new_name="created_by",
        ),
    ]
